name: "Get the default bucket name for artifacts"
description: "N/A"
inputs:
  bucket:
    description: |
      "Handy parameter. Returns the same value if non-empty.
      Leave empty to use the implicit 'gh-runs_<org-name>_<repo-name>'. 
      For the implicit bucket name, dots are replaced by hyphens, slashes are replaced by underscores. The bucket name should be lowercase. For 'My-Dear-Org/my.repo', we get 'gh-runs_my-dear-org_my-repo'"
    required: false

outputs:
  bucket_name: 
    description: "The default bucket name, based on run id and repo url"
    # Fun hack until we find a proper way: since only one of them will be executed, joining them gives us the correct result!
    value: ${{ steps.bucket_namer_unix.outputs.value }}${{ steps.bucket_namer_win.outputs.value }}

runs:
  using: "composite"
  steps: 
      # Note: code duplication was the only way atm

      - name: Get bucket name [UNIX]
        id: bucket_namer_unix
        if: runner.os != 'Windows'
        shell: bash
        run: chmod +x out_bucketname.sh && ./out_bucketname.sh "${{ inputs.bucket }}"

      - name: Get bucket name [WIN-WSL]
        id: bucket_namer_win
        if: runner.os == 'Windows'
        shell: wsl bash --noprofile --norc -euo pipefail "$(wslpath '{0}')"
        run: chmod +x out_bucketname.sh && ./out_bucketname.sh "${{ inputs.bucket }}"
