name: "Get the default bucket name for artifacts"
description: "N/A"
inputs:
  bucket:
    description: |
      "Handy parameter. Returns the same value if non-empty.
      Leave empty to use the implicit 'gh-runs_<org-name>_<repo-name>'. 
      For the implicit bucket name, dots are replaced by hyphens, slashes are replaced by underscores. The bucket name should be lowercase. For 'My-Dear-Org/my.repo', we get 'gh-runs_my-dear-org_my-repo'"
    required: false

outputs:
  bucket_name: 
    description: "The default bucket name, based on run id and repo url"
    # Fun hack until we find a proper way: since only one of them will be executed, joining them gives us the correct result!
    value: ${{ steps.bucket_namer_unix.outputs.value }}${{ steps.bucket_namer_win.outputs.value }}

runs:
  using: "composite"
  steps: 
      # Note: code duplication was the only way atm

      - name: Get bucket name [UNIX]
        id: bucket_namer_unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          s="${{ github.action_path }}/out_bucketname.sh"
          echo $s
          echo $s
          echo $s
          chmod +x "$s" && "$s" "${{ github.repository }}" "${{ inputs.bucket }}"

      # - uses: Vampire/setup-wsl@v1
      #   with:
      #       distribution: Ubuntu-18.04

      - name: Get bucket name [WIN-WSL]
        id: bucket_namer_win
        if: runner.os == 'Windows'
        # Thanks https://github.com/actions/virtual-environments/issues/50#issuecomment-663917469
        shell: wsl bash --noprofile --norc -euo pipefail "$(s="$(wslpath '{0}')" && sed -i 's/\r$//' "$s" && echo "$s")"
        run: |
          s=$(wslpath "${{ github.action_path }}/out_bucketname.sh")
          echo "Temp fix via wslpath: convert paths like C:\\path to c:/mnt/path"

          chmod +x "$s" && "$s" "${{ github.repository }}" "${{ inputs.bucket }}"
