name: "Get the default bucket name for artifacts"
description: "N/A"
inputs:
  bucket:
    description: |
      "Handy parameter. Returns the same value if non-empty.
      Leave empty to use the implicit 'gh-runs_<org-name>_<repo-name>'. 
      For the implicit bucket name, dots are replaced by hyphens, slashes are replaced by underscores. The bucket name should be lowercase. For 'My-Dear-Org/my.repo', we get 'gh-runs_my-dear-org_my-repo'"
    required: false

outputs:
  bucket_name: 
    description: "The default bucket name, based on run id and repo url"
    value: ${{ steps.bucket_namer.outputs.value }}

runs:
  using: "composite"
  steps:  
      - name: Get shell name to use
        id: shell_namer1
        if: runner.os == 'Windows'
        shell: wsl bash --noprofile --norc -euo pipefail "$(wslpath '{0}')"
        run: |
          echo "::set-output name=value::wsl bash --noprofile --norc -euo pipefail \"$(wslpath '{0}')\""
          echo "V_SHELL=wsl bash --noprofile --norc -euo pipefail \"$(wslpath '{0}')\"" >> $env:GITHUB_ENV

      - name: Get shell name to use
        id: shell_namer2
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "::set-output name=value::bash"
          echo "V_SHELL=bash" >> $GITHUB_ENV

      - name: Get bucket name
        id: bucket_namer
        # Fun hack until we find a proper way: since only one of them will be executed, joining them gives us the correct result!
        # shell: ${{ steps.shell_namer1.outputs.value }}${{ steps.shell_namer2.outputs.value }}
        shell: ${{ env.V_SHELL }}
        run: |
          b="${{ inputs.bucket }}"
          if [ -z "$b" ]; then
            repo="${{ github.repository }}"
            b_no_slashes=$(echo "$repo" | sed "s/\//_/g")
            b_no_dots=$(echo "$b_no_slashes" | sed "s/\./-/g")
            b_lowercase=$(echo "$b_no_dots" | (tr '[:upper:]' '[:lower:]'))
            b=gh-runs_"$b_lowercase"
            echo "Using $b as implicit bucket name"
          fi
          echo "::set-output name=value::$b"
