name: "Get the default bucket name for artifacts"
description: "Uses main-quest/actions.gsutil"
outputs:
  bucket_name: 
    description: "The default bucket name, based on run id and repo url"
    value: ${{ steps.bucket_namer.outputs.value }}
runs:
  using: "composite"
  steps:  
      - name: Get bucket name
        id: bucket_namer
        shell: bash
        run: |
          repo="${{ github.repository }}"
          b_no_slashes=$(echo "$repo" | sed "s/\//_/g")
          b_no_dots=$(echo "$b_no_slashes" | sed "s/\./-/g")
          b_lowercase=$(echo "$b_no_dots" | (tr '[:upper:]' '[:lower:]'))
          b=gh-runs_"$b_lowercase"
          echo "Using $b as implicit bucket name"
          echo "::set-output name=value::$b"
